# (PART) ...with R {-}

# Code Organsation

The essence of Agile Data Science, continuously delivering an uptaded product, can only be achieved when the code is of high quality. Many data scientists, especially those who are drawn to R, have a background other than software development. Writing software is something we do to solve problems in our professional field, such as statistics, ecology, actuary or one of the many other fields R is used. The code is typically written interactively with the data. Write a a few lines of code, run the data set at hand, check if the results match your expectations, if it does go on and write a few more lines of code. This approach might be fine for a quick explorative data analysis in which you write code to answer a few ad hoc questions. It is not fine for large scale projects in which the data prodcut should be reliable and stable, because this way of working results in low reproducibility and flexibility towards new situations. 

Reproducibility is low because code is not developed as part of an end-to-end product, but incrementally in which each time a bit of code is added. We could call this the *random walk programming*, the next step is determined only by the current state of the code and data. 
